### ISSUE TITLE
Use Looker as export UI

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#118]
Sending Bearden data to Redshift and letting team members self-serve exports using Looker may be the smoothest and most efficient way to export data. Looker is already a powerful tool for building data sets that the Artsy team at large is familiar with.

## Thoughts
- Using Looker, team members can create CSVs of Bearden data of selected fields applying selected filters 
- Using Looker, we can track the path of a Bearden lead through the sales pipeline, since Salesforce data is there as well.
- Only highest ranking field data will be sent to Redshift and into Looker, at least at first.

**Comment by jonallured** [comment]
I think it's safe to close this one with #139 merged, but feel free to reopen if I missed something!!
