### ISSUE TITLE
Giving "updated_website" column priority

### ISSUE THREAD

**Issue by mdole** [artsy/bearden#121]
As per our conversation yesterday, I've uploaded a CSV called roster_orgs_condensed_2 with an "updated_website" column to the [Dropbox](https://www.dropbox.com/home/Bearden_Burden_Outsourcer_Verifications_Data/oursourcer_source_data).  If possible, would be great to replace the existing websites with updated websites where possible. I also added data from the very first Burden outsourcer project to the same CSV (if you'd prefer it in its own CSV, let me know).

Note on the data from the first batch (row 46747 on): when this was collected, we were not asking outsourcers to label they type of organization, instead only asking "Is this an art gallery?" Therefore, I labelled all those marked "No" as "Other," though they may in fact be auction houses, museums, etc.

As I was writing this, I also realized we might be going about this in a more-difficult-than-necessary manner. Instead of having an entirely new column, could we simply replace the existing sites in the "website" column with those in the "updated_website" column? Would the importer give them higher priority and update accordingly? If this is the case, I can easily paste over and reupload.

cc @gnilekaw @madeleineb

**Comment by madeleineb** [comment]
Matt and I just discussed, and it should be noted that everything in roster_orgs_condensed.csv is ALSO in roster_orgs_condensed_2.csv. I will be working off of those.

@gnilekaw what do you think of just using this pasting-over solution to importing corrected websites in `updated_website`?

**Comment by gnilekaw** [comment]
Pasting over should be fine. 

We're getting data from Burden by the ID, so if the sheet differs from Burden that's OK.

**Comment by madeleineb** [comment]
Okay. Sounds like we just need to make sure to use this website rather than Burden's as the unique identifier.

**Comment by gnilekaw** [comment]
Closing this because seems like everyone's on the same page about what needs to be done: Simply use the preferred website in the website column.
