### ISSUE TITLE
upon import, handle variation in website URLs

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#131]
- Bearden should recognize all versions of a website—`http://` `https://` `www.` and no `www.`—as the same site. Upon import, websites should match regardless of prefixes.
- Suffixes such as `/` and `/en` should also not create duplicates.

@gnilekaw not part of MVP, since we can handle this offline while prepping CSVs for import for now (find & replace!)

discussed in #82

**Comment by madeleineb** [comment]
One clarification re: what we were discussing today, @gnilekaw and @jonallured — you mentioned that here we'll capture redirects. Does that mean upon import, we will also store both instances of a URL, i.e. the `.com` and the `.co.uk` versions?

**Comment by jonallured** [comment]
Good question - unless you feel strongly, we'd like to only store the resolved version. The unaltered version would always be available on the RawInput, so we wouldn't be throwing anything away.

**Comment by madeleineb** [comment]
@jonallured That makes sense to me, so long as it wouldn't affect our ability to match in the future, since we'd always be doing the step of redirecting. So, the next time an import includes `example.com` and that redirects to `example.co.uk`, even if we were only storing `example.co.uk` we will know it's the same.

**Comment by jonallured** [comment]
@madeleineb update on this: @gnilekaw and I ended up deciding that it made more sense to just store every version of the website. So, if your import CSV looks like this:

```
website,organization_name
artsy.net,Artsy
```

Then you'll actually end up with the following `Website` records:

* http://artsy.net, status: 301
* https://www.artsy.net, status: 200

So, if future imports used *either* of those URLs, we'd have a match. 👍 

Just to share a little more - this structure allows us to store "bad" websites, so if the URL 404s (`artsy.net/lolwut`), we'll still store that. If, however, the URL is just complete garbage (`gallery.hoof`), then we'll blow up the row and report the error.

**Comment by madeleineb** [comment]
Great, I'm glad this solution preserves more information! Makes total sense to store both the status that we're getting back and all non-bad URLs, and I do like the fact that in the future if the status changes we can use that as a signal that it might be "closed".
