### ISSUE TITLE
[MVP] In UI, see per-field rankings of data sources

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#133]
It would be great to be able to see the per-field rankings of different data sources, just to have visibility in the UI into what's going to happen behind the scenes when we flatten data into a CSV for export taking the highest-ranked source.

Something, perhaps, like:

| Name | Email | Phone |
|----|----|----|
| 1. Factual | 1. CB | 1. Factual |
| 2. Burden | 2. HumanOutsourcer | 2. CB |
| 3. CB | 3. Factual | 3. Burden |
| ... |... |... |

Note that there's no need to be able to adjust the rankings of these sources yet through a UI, which is #110.

**Comment by jonallured** [comment]
For posterity: talked about where this might go with @madeleineb and we decided it made sense for `/sources`, so that's where I'll put this table.
