### ISSUE TITLE
Handle the concept of an organization being "closed"

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#138]
## Requirements:
- [ ] Add field for `in_business` which defaults to `true`
- [ ] Add per-field ranking for this field
- [ ] Include this field in data pushed to Redshift.

-----
Indicators of an organization being closed might be:

- Marked "Closed" on Yelp 
- Website returns a 404 (this could also just mean we have the wrong web address 🤔 )
- A human indicates it's closed (<-- strongest indicator)
- Low existence score from Factual

If an organization is closed, we still do want to keep it in Bearden, so that the next time we discover it in another source, we can hang on to this information.

cc: @jonallured @gnilekaw

**Comment by jonallured** [comment]
@gnilekaw and I discussed and we're thinking we just add a boolean column to the organizations table called `in_business` or something. It would default to true.

Then in the CSV an importer sends up, we'd add support fo a column by the same name. If that column were present and contained the string 'false', then we'd flip the bool over to false.

Finally, over in the job that exports data over to Redshift, we could exclude those organizations. Or we could also just export everyone and then include that column in case that data would be useful.

How does that sound @madeleineb?

**Comment by madeleineb** [comment]
@jonallured That sounds like it would work well. Factual, by contrast, handles this with an existence score 0-1 rating the likelihood that something "exists", which takes into account a number of metrics, but this is probably a) too complex for the sake of just knowing if something is open or closed, and b) wouldn't play nice with our per-field authority ranking system.

Seems to me that we should evaluate the likelihood of open/closed based on the authority of the source, just like anything else, right? I.e. if a human marks it closed even though we previously thought it was open, we should surface that information in exports, as it's higher authority.
