### ISSUE TITLE
Add fields for city and country

### ISSUE THREAD

**Issue by gnilekaw** [artsy/bearden#146]
I'm reasonably certain that this will be the first thing people want to search by. 

We could add this to the geocoder job easily.

**Comment by madeleineb** [comment]
Good call. Seems like the Burden city/country data is also pretty clean, and it would be good to be able to import that smoothly.

**Comment by gnilekaw** [comment]
@madeleineb Lmk if you want me to get this in for the mvp

**Comment by madeleineb** [comment]
@gnilekaw We're definitely gonna do it anyway, so if it's fast to add the geocoder job, while not part of that 100% bare-minimum-critical information, it will help the MVP goal of sending useful info on. Let's do it.
