### ISSUE TITLE
Add pre-flight step for verifying Import file encodings

### ISSUE THREAD

**Issue by jonallured** [artsy/bearden#164]
The `ParseCsvImportJob` needs to have the data it's working with be in UTF-8 format. Add a step to the Import process that does some checks on the Import, one of which is the encoding. While researching this today, I found this library:

https://github.com/brianmario/charlock_holmes

Great library name or greatest?

**Comment by madeleineb** [comment]
@jonallured  Here's a few test files with windows encoding:

https://www.dropbox.com/s/mi8neaw6pn1j7sa/TEST-windows-encoding-contemporary-art-venues.csv?dl=1
https://www.dropbox.com/s/t3xh37uuual344x/TEST-windows-encoding-artforum.csv?dl=1
https://www.dropbox.com/s/xuytgf1bi3rsxja/TEST-windows-encoding-global-gallery-guide.csv?dl=1
