### ISSUE TITLE
Method to return Bearden ranked records from email's domain, send to Salesforce

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#191]
@cfinsness and @sperle and I discussed the best way to automate for one very specific Bearden use case: _A new email is created in Marketo; we need to know more about that contact; Bearden may contain a matching record based on the domain of the email._

### Requirements
- When a new contact is created in Marketo (and syncs to Salesforce), Salesforce can fetch matching data from Bearden (via Fulcrum via Redshift?)
- Matching works based on the domain level; so, if the record in Marketo is attached to `joe@example.com`, and the record in Bearden is `example.com, sheila@example.com`, Salesforce gets the record for the Org based on the identifier `example.com`.

### Not included here

-  A total automated integration that sends new records in Bearden to Marketo. For the next few months, this will continue to be done via manual exports (but we don't plan for this to be permanently manual).

cc: @gnilekaw

**Comment by madeleineb** [comment]
Adding a note here based on my conversation with @cfinsness and @nicholassewitz today: we discussed that the best way to tackle this may be to leverage Fulcrum to get Salesforce to talk to Redshift. Because there's a 1:1 sync between Marketo <> Salesforce, this would also deliver the Bearden info back to Marketo.

@tayapage6 , I'd like to get your input on this approach and prioritizing this work item before next round of engineering time on Bearden.

**Comment by cfinsness** [comment]
+ @sperle

**Comment by madeleineb** [comment]
Issue moved to [artsy/collector-experience #253](https://github.com/artsy/collector-experience/issues/253) via [**ZenHub**](https://www.zenhub.com/)
