### ISSUE TITLE
Schedule geocoder job on production

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#193]
Done nightly?

Should also kick off sync to Redshift.

**Comment by gnilekaw** [comment]
OK, let's see if this 🐶  can hunt.

<img width="771" alt="screen shot 2017-04-19 at 2 19 45 pm" src="https://cloud.githubusercontent.com/assets/7292475/25195331/4cc8d3da-250b-11e7-90e6-65725f7ef4ce.png">
