### ISSUE TITLE
Run org type and in business data migrations

### ISSUE THREAD

**Issue by jonallured** [artsy/bearden#242]
Once both #235 and #240 have been merged, then we should copy production data to staging and run the data migrations there. @madeleineb was also going to do some spot checking.

When we're comfortable with the results, then we can migrate the data on production:

* [x] turn maintenance mode on
* [x] scale worker and export_worker to zero
* [x] take database backup
* [x] save backup somewhere safe
* [x] run data migration rake tasks
* [x] scale worker and export_worker to 1
* [x] turn maintenance mode off

Which would look something like this:

```
$ heroku maintenance:on -r production
$ heroku ps:scale worker=0 export_worker=0 -r production
$ heroku pg:backups:capture -r production
$ heroku pg:backups:download -r production
$ heroku run rake tag_type_data_migration in_business_data_migration -r production
$ heroku ps:scale worker=1 export_worker=1 -r production
$ heroku maintenance:off -r production
```

**Comment by jonallured** [comment]
After running this on staging, I've revised my formula slightly:

```
$ heroku maintenance:on -r production
$ heroku ps:scale worker=0 export_worker=0 -r production
$ heroku pg:backups:capture -r production
$ heroku pg:backups:download -r production
$ heroku run rake in_business_data_migration -r production
$ heroku run rake tag_type_data_migration -r production -s Standard-2X
$ heroku ps:scale worker=1 export_worker=1 -r production
$ heroku maintenance:off -r production
$ heroku run rake redshift:force_sync -r production
```

The biggest change is splitting up the tasks and doing the tag-type migration on a bigger dyno so that it doesn't run out of memory.

**Comment by jonallured** [comment]
I completed the migration this morning, but I'll let @madeleineb do the honors of closing the ticket once she's satisfied that the data on production looks good. 👍

**Comment by madeleineb** [comment]
@jonallured Awesome work here! Everything looks good as far as I can tell from my spot checks. I noted fewer `closed` organizations than I would have expected, but this is because many of their websites are dead, which means that they show up in import error logs instead. That's all good.

Thanks again!
