### ISSUE TITLE
Compile detailed stats on import successes

### ISSUE THREAD

**Issue by gnilekaw** [artsy/bearden#71]
When importing a CSV it will be helpful to know the following (in no order):

- Total records
- Total imported
- Total errors
- Name of source 
- Import ID
- Total orgs, locations, emails, phone numbers and websites created

This becomes particularly important when the number of records are very high.

**Comment by madeleineb** [comment]
@jonallured Seems to me that this is being tackled in the minimal UI for testing, though you mentioned that it doesn't yet support error handling or feedback?

**Comment by jonallured** [comment]
Yeah, the basics of this issue are covered by the Import show page. What we don't have are counts on the orgs, locations, emails, etc that are generated, but my feeling is we skip that for now and only come back to it after people are using it and if they ask about it.

The other thing that we don't have (yet) is anything for errors, but I'm working on that too.

**Comment by madeleineb** [comment]
Okay, @jonallured then I will consider this detailed feedback on import successes post-MVP, and distinct from error-handling for imports, which you're working on already.

**Comment by gnilekaw** [comment]
We got this!
