### ISSUE TITLE
Test importing tags with factual data sample

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#72]
Before confirming the buy, we're asking for a sample of data from Factual for eg. 2 different cities (one that's easier to verify, one that we've had a hard time finding leads for).

Factual data will contain tags, and it would be great to test tag imports, mapping their sample to our chosen tag structure ( #60 and #46 ). This will involve some offline matching (**MB**), and figuring out how to structure the import CSV for tags.

**Comment by gnilekaw** [comment]
We have tag support. Closing.
