### ISSUE TITLE
When's the right time to build the Marketo Webhook?

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#77]
(expecting this will be closed in favor of more granular and specific issues)

A Marketo webhook + Bearden MVP requirements = we can take Burden off life support

Let's do this in a manual way right now using csv exports, then figure out what we're going to automate. 

_Before we can do this:_
- Production data in Bearden needs to be with a good point
- Need to be explicit about what Marketo is expecting from Bearden
    - checking for existing data in Bearden, pass it back to Marketo
    - _More up for debate is, whether a new gallery contact in Marketo should pass that back to Bearden?_

What's the authority of Marketo data?
- Sometimes people lie when they self-identify, saying they're a gallery.

**Comment by gnilekaw** [comment]
Closing this cause https://github.com/artsy/bearden/issues/191
