### ISSUE TITLE
Clean up and import S3 Burden data

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#82]
We'll only import data from S3 that has a `website`, which would include only some of the sources.

[_Source: All S3 data as of Jan 19_](https://docs.google.com/spreadsheets/d/1s_UNAS_Nt3k-BXiMAIDO_TQD6MlDo4Iv7tgvdlttmmY/edit#gid=370364077)

Manually cleaning will probably be the easiest way to deal with getting this data into a nicely importable format—for example, some phone numbers are in the website field—and I'm happy to do that offline.

**Comment by madeleineb** [comment]
Alrighty, I've tagged what I can safely tag, and created some compiled "_for-import-..." csv files for each of the sources. 

@gnilekaw how are we handling variation in website URLs? Should I strip out the http://'s and www.'s or will that happen during matching?

**Comment by gnilekaw** [comment]
@madeleineb, good catch. We currently don't have validation like this for any fields. As it stands, if you had the same website two times, one with `http` and one with `www`, then you would get two orgs. Will you make a ticket for that and let us know if it should be part of the mvp?

**Comment by madeleineb** [comment]
CSVs are cleaned up and ready to go, barring some errors that will need to be cleaned up after import.
