### ISSUE TITLE
Independently confirm record counts

### ISSUE THREAD

**Issue by gnilekaw** [artsy/bearden#91]
[WIP]: I'd like to run these imports again to check the numbers are correct.

🎉 We've uploaded 20,746 organizations into Bearden (local machine) and only saw a 2% error rate.* 

To get this data, we took two spreadsheets that were validated by outsourcers and, using the Burden IDs, created complementary data from Burden records. The results are the four sheets below.

As you can see there are probably some mistakes. For instance, I would expect the number of Organizations to be equal or less than the total count of outsourcer records (16,678). But the org count is more than the number of outsourcer records!

Additionally, there are probably more subtle errors within emails, phone numbers, and locations. 

It would be a huge help to Jon and I if we could get some independent validation on how many records we should expect. Not sure who we can ask for help with this. Perhaps marketing or analytics?

## Source Data

File | Rows in CSV
---|---
artist-rosters-batch-2-combined.csv | 6,670
burden-complement-artist-rosters-batch-2-combined.csv | 30,722
outsourcer-artist-rosters-batch-1-combined.csv | 10,008
burden-complement-outsourcer-artist-rosters-batch-1-combined.csv | 27,545

## Created Records

Record Type | Total Count
---|---
Emails | 29,311
Organizations | 20,746
Websites | 20,738
Organization Names | 16,137
Locations | 15,729
Organization Tags | 14,955
Phone Numbers | 13,853

*(The working hypothesis is that these are duplicate entries, but we'll [find out](https://github.com/artsy/bearden/issues/90) for sure next week.)

**Comment by madeleineb** [comment]
@gnilekaw Following up from our slack convo last week, let me know if you need anything more from me here!
